# Import the LLM interface to call for summaries
from ..llm import react_with_llm

# This function prepares a summarization prompt and sends it to the LLM
def summarize_text(text: str) -> str:
    """
    Generates a summary of the provided document text in either paragraph or bullet-point format using the LLM.

    Parameters:
    - text (str): The full document content as a string.

    Returns:
    - str: The summary generated by the LLM.
    """
    # Only send the first 3000 characters to avoid overloading the LLM
    if format == "bullets":
        prompt = f"Summarize the following document in bullet points:\n\n{text[:3000]}"
    else:
        prompt = f"Summarize the following document:\n\n{text[:3000]}"
    
    # Format the message as a single-user prompt for the LLM API
    messages = [{"role": "user", "content": prompt}]
    return react_with_llm(messages)

